format_version: 4
pipelines:
  deploy_to_prod:
    group: kubernetes
    display_order: 3
    environment_variables:
      NAMESPACE: gocd
    secure_variables:
      KUBE_TOKEN: AES:OvRqMzN0lFBfJ9Fb40xuow==:7K58KOUf6C6yDpnJBj53Mdsp7xiSQ8AznqynY/2WHXpTdlhKT2c62l9bEKmUvkO2iMoz17iufZin7A6E/MFrRr0kva2fX1BeLwzx1l789gxNTEIWFRPCoOY7nm+hAV97O7eGI/Z1SEoF2Vik890a/2OZ2Xg96KI1xPhCnoVqyoGGoD3ERb4xHehFFUpO0h7dojMnuL24RgKy7G3yPXdBJZj09elmmqWnGYmUNfZwJo04ldvAd61YL1XTHwZDaE0Gd24dfLy1dGy7gDVJHRWdnPBU5xAd1N4t81wzLamm3ugE/3xffwrkz10QPd7ifZE3a+UBCfYFBGitv82CQ1CW4xFCHe7he9/HR5yjCBjB5hd++rpqC25JL4GLPkNPLg4pJ73RJywNcaO1DT4cQ++MmYO1TB20M6lQQ0+P1BpaQLuh0hsoSB5gMXbz5HpNiH5+54rgeicFKv7koq4fLeA4i2ZagxtmR4EZ9KSx5mJEvObnWG8pijfz5q7yUfZCdbnZtfAQqi5wiTe9zmgA5wqCKvRiQuFIfdV+7FqXPODUr7j1g+LvcNcfPOa1BinTYmghVt/BPO9A5AW5dbUlqYkq4d2/uSfPWljFwgOHhqb6nM8AGDp+5vWS9Cl0D0UzL3q+exI1vOge0KzZIqBGkMKMKON2zUK4/Jc5o+E54+qZ7FFHCERtJ60Uw6oI/IOCiDR4eWb+gjghFL2OMwPidUMEY3jdJAXBFsq3ht58m5O+KbmyucshzKJztIoz5RGfcwNvcWAs4Ge7LefeK5eVLg0uPXdniLgXOoiuLmsYN43h5WvCcJ1Bw7WmQE1gVJUrGI8dr1/7X+txWnG3B2m4ujXA6xbK2k0RDHEViG8OhsVXB1UITejwd2mbcwxVyd1ujbbp5rkLfHZpS3DTVuHu9n6r/trBYud1ctYY4I/BmdjLEypMVUfWHZf4cW8s2RlRSfUMC1hEk/gFAJ7Oe1ZG4bRIUmlcm/PD0LIX7VjMhT6GVPN0jTro2nd4xdPv36rtkfEgnxGXDrSZGTEzehVc1uP0I9H4BFEccHfa6NASJ9zwJ09iBYJ4nf+cHh9MnrqeJCViZoWlxH1aE8MEqTmun7DdLxHK5uczmYd6u7agcGurtIpiQ6a6J3r83E5xNlfJYlaiOmD2AGaU9NDH+1DEmcTFZw==
    materials:
      build:
        pipeline: build_and_package
        stage: test_stage
      SourceCodeRepo:
        git: https://github.com/dbirks/node-bulletin-board.git
        shallow_clone: false
    stages:
    - deploy_to_prod:
        approval:
          type: success
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: /bin/bash
                arguments:
                - -c
                - ./app-deployment.sh
                run_if: passed
